### PR TITLE
Enabling SSL for insights

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by mtyaka** [comment]
:+1: 

It would be nice to open an upstream PR for this.

**Comment by antoviaque** [comment]
+1 to the upstream PR - the fact that it's ansible code rather than python code doesn't change our approach regarding code drift and contributions.

**Comment by e-kolpakov** [comment]
@antoviaque @mtyaka oh, come on, I've created [upstream PR](https://github.com/edx/configuration/pull/2947) minutes after this one merged :)

**Comment by antoviaque** [comment]
@e-kolpakov Great then, perfect : ) To my discharge, I had checked the Jira ticket but didn't find a link to the upstream PR :p

**Pull request merged**
